name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Secret in Environment Variable
        run: echo "Using secret key"
        env:
          JWT_EXPIRATION: ${{ secrets.JWT_EXPIRATION }}